<h4> [Problem 1] Manually calculate the matrix product</h4>

A 

⎡−1  2  3⎤

⎢ 4 -5  6⎥

⎣ 7  8 -9⎦


B

⎡ 0  2  1⎤

⎢ 0  2 -8⎥

⎣ 2  9 -1⎦

AB ( multiply A row with B colomn)

⎡−1x0 + 2x0 + 3x2   −1x2 + 2x2 + 3x9  −1x1 + 2x-8 + 3x-1⎤

⎢ 4x0 + -5x0 + 6x2  4x2 + -5x2 + 6x9  4x1 + -5x-8 + 6x-1⎥

⎣ 7x0 + 8x0 + -9x2  7x2 + 8x2 + -9x9  7x1 + 8x-8 + -9x-1⎦


AB final result

⎡  6   29  -20⎤

⎢  12  52   38⎥

⎣ -18 -51  -48⎦

<h4>[Problem 2] Calculation by NumPy function</h4>

In [45]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(np.dot(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<h4>[Problem 3] Implement the calculation of a certain element</h4>

In [10]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
# sum(a[0, 1, :] * b[0 , :, 1])
# print(a_ndarray[0,0]*b_ndarray[0,0])
# print (np.zeros((3,len(a_ndarray[0]))))
# result = [[0,0,0],
#          [0,0,0],
#          [0,0,0]]
result = np.zeros((3,3), dtype=int)
# iterate through rows of a_ndarray
for i in range(len(a_ndarray)):
   # iterate through columns of b_ndarray
   for j in range(len(b_ndarray[0])):
       # iterate through rows of b_ndarray
       for k in range(len(b_ndarray)):
           result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
print("the value of 0th row and 0th column", result[0][0], "\n")
print(result)

the value of 0th row and 0th column 6 

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<h4> [Problem 4] Creation of a function that performs matrix multiplication</h4>

In [11]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
# sum(a[0, 1, :] * b[0 , :, 1])
# print(a_ndarray[0,0]*b_ndarray[0,0])
# print (np.zeros((3,len(a_ndarray[0]))))
# result = [[0,0,0],
#          [0,0,0],
#          [0,0,0]]
def product(a,b):   
    result = np.zeros((3,len(b[0])), dtype=int)
    # iterate through rows of a_ndarray
    for i in range(len(a_ndarray)):
        # iterate through columns of b_ndarray
        for j in range(len(b_ndarray[0])):
            # iterate through rows of b_ndarray
            for k in range(len(b_ndarray)):
                result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
    return result

# print(product(a_ndarray,b_ndarray))

<h4> [Problem 5] Judging the input for which the calculation is not defined </h4>

In [12]:
import numpy as np
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
def product(a,b):   
    if(len(a)== len(b[0])):
        result = np.zeros((3,len(b[0])), dtype=int)
        # iterate through rows of a_ndarray
        for i in range(len(a_ndarray)):
            # iterate through columns of b_ndarray
            for j in range(len(b_ndarray[0])):
                # iterate through rows of b_ndarray
                for k in range(len(b_ndarray)):
                    result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
        return result
    else:
        return "this matrix can not be multiplied"
print(product(d_ndarray, e_ndarray))

this matrix can not be multiplied


<h4> [Problem 6] Transpose </h4>

In [13]:
import numpy as np
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
def product(a,b):   
    if(len(a)== len(b[0])):
        result = np.zeros((3,len(b[0])), dtype=int)
        # iterate through rows of a_ndarray
        for i in range(len(a)):
            # iterate through columns of b_ndarray
            for j in range(len(b[0])):
                # iterate through rows of b_ndarray
                for k in range(len(b)):
                    result[i][j] += a[i][k] * b[k][j]
        return result
    else:
        return "this matrix can not be multiplied"
# print(product(d_ndarray, e_ndarray))
print(product(np.transpose(d_ndarray), e_ndarray))


[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
