### Introduction to Machine Learning Pre-class assignment 3 Utilization of Object Orientation

#### [Problem 1] List of classes used so far

### classes

- pandas.read_excel()
- pandas.Series()

- matplotlib.plot()
- matplotlib.subplots()

- sklearn.tree
- sklearn.svm







#### [Problem 2] Enumeration of methods and instance variables that have been used so far

### Methods

- pandas.columns()
- pandas.iloc()
- numpy.itemsize()
- numpy.reshape()
- pandas.loc()

---
### instance variable
- ndarrary.item
- ndarrary.itemset
- ndarrary.tolist
- ndarrary.data
- ndarrary.size

#### [Problem 3] Create a standardized class by scratch

In [24]:
class ScratchStandardScaler():
   
    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
    def transform(self, X):
        X_scaled = (X-self.mean_)/self.var_
        return X_scaled

In [25]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
sct_scaler = ScratchStandardScaler()
sct_scaler.fit(X)
print("mean :", sct_scaler.mean_)
print("distributed :", sct_scaler.var_)
X_std = sct_scaler.transform(X)
print(X_std)

mean : [4.86 3.31 1.45 0.22]
distributed : [0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


#### [Problem 4] Creating a class that performs four arithmetic operations

In [26]:
def judge_type(value_to_judge):
    if not isinstance(value_to_judge, (int,float)):
        print("please input numbers only")
        return False
    else:
        return True

class ArthClass():
   
    def __init__(self, value):
        if(judge_type(value)):
            self.value = value
            print("Initial value {} has been set".format(self.value))
        else:
            self.value = value

    def add(self, value2):
         if judge_type(self.value) and  judge_type(value2):
             self.value += value2
         else:
             self.value = " can not be calculated because one of the value is not a number"

    def sub(self, value2):
         if judge_type(self.value) and  judge_type(value2):
             self.value -= value2
         else:
             self.value = " can not be calculated because one of the value is not a number"

    def mult(self, value2):
         if judge_type(self.value) and  judge_type(value2):
             self.value *= value2
         else:
             self.value = " can not be calculated because one of the value is not a number"

    def div(self, value2):
         if judge_type(self.value) and  judge_type(value2):
             self.value /= value2
         else:
             self.value = " can not be calculated because one of the value is not a number"

example = ArthClass(5)
print("value : {}".format(example.value))

example.add(3)
print("Additon value : {}".format(example.value))

example.sub(3)
print("Subtraction value : {}".format(example.value))

example.mult(3)
print("Multiplication value : {}".format(example.value))

example.div(3)
print("division value : {}".format(example.value))

example = ArthClass('p')
example.add(3)
print("Additon with wrong input : {}".format(example.value))

Initial value 5 has been set
value : 5
Additon value : 8
Subtraction value : 5
Multiplication value : 15
division value : 5.0
please input numbers only
please input numbers only
Additon with wrong input :  can not be calculated because one of the value is not a number
